import type { Metadata } from 'next';
import { Alexandria } from 'next/font/google';
import './globals.css';

const alexandria = Alexandria({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Todo App | Organize Your Tasks',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
      </head>
      <body className={alexandria.className}>{children}</body>
    </html>
  );
}
